name: Changelog

on:
  workflow_dispatch:
  # Trigger analysis when pushing in master or pull requests,
  # and when creating a pull request.
  release:
    types:
      - published

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Changelog
        uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
